### PR TITLE
Add --exit-when option

### LINKED ISSUE #279: Exit when queue(s) empty
I would suggest adding the following option:

```
--exit-when-empty
```

It is obvious what should happen with 1 queue. With 2+ queues it would wait until all queues are "empty".

There's a few different ways of doing this from what I understand. I think there's no need to look whether the queues are empty if there were incoming messages in the last second. So I would wait 1 second of idle time before checking whether the queue is empty.

I do not see a reason to configure the method/timeout for checking.

I would be OK with an option `--exit-when-idle` as well for what it's worth. Or both. If going for both then perhaps `--exit-when=empty | idle`.

The exit reason should be normal (0).

### PR DESCRIPTION
**Pull request by acogoluegnes**
Fixes #279

### CODE REVIEW

**Comment by acogoluegnes** [comment]
```
cd /tmp
git clone git@github.com:rabbitmq/rabbitmq-perf-test.git
cd rabbitmq-perf-test
git checkout rabbitmq-perf-test-279-consumer-activity
make binary
tar xf target/rabbitmq-perf-test-2.17.0-SNAPSHOT-bin.tar.gz
```

```
docker run -it --rm --name rabbitmq -p 5672:5672 -p 5552:5552 -p 15672:15672 rabbitmq:3.9-management
```

```
rabbitmq-perf-test-2.17.0-SNAPSHOT/bin/runjava com.rabbitmq.perf.PerfTest -x 1 -y 0 --queue test --pmessages 50000
rabbitmq-perf-test-2.17.0-SNAPSHOT/bin/runjava com.rabbitmq.perf.PerfTest -x 0 -y 1 --queue test --consumer-rate 10000

rabbitmq-perf-test-2.17.0-SNAPSHOT/bin/runjava com.rabbitmq.perf.PerfTest -x 1 -y 0 --queue test --pmessages 50000
rabbitmq-perf-test-2.17.0-SNAPSHOT/bin/runjava com.rabbitmq.perf.PerfTest -x 0 -y 1 --queue test --consumer-rate 10000 --exit-when idle
id: test-153245-095, starting consumer #0
id: test-153245-095, starting consumer #0, channel #0
id: test-153245-095, time: 1.000s, received: 7911 msg/s, min/median/75th/95th/99th consumer latency: 0/0/0/0/0 µs
id: test-153245-095, time: 2.000s, received: 10001 msg/s, min/median/75th/95th/99th consumer latency: 0/0/0/0/0 µs
id: test-153245-095, time: 3.000s, received: 9981 msg/s, min/median/75th/95th/99th consumer latency: 0/0/0/0/0 µs
id: test-153245-095, time: 4.000s, received: 10011 msg/s, min/median/75th/95th/99th consumer latency: 0/0/0/0/0 µs
id: test-153245-095, time: 5.000s, received: 10001 msg/s, min/median/75th/95th/99th consumer latency: 0/0/0/0/0 µs
test stopped (No activity for 1 second for queue test)
id: test-153245-095, sending rate avg: 0 msg/s
id: test-153245-095, receiving rate avg: 8028 msg/s


```

**Review by lhoguin — APPROVED** [review]

**Comment by lhoguin** [comment]
All good!

One thing I noticed is:

```
rabbitmq-perf-test-2.17.0-SNAPSHOT/bin/runjava com.rabbitmq.perf.PerfTest -x 0 -y 1 --queue test5 --predeclared --consumer-rate 10000 --exit-when idle
id: test-104850-534, starting consumer #0
id: test-104850-534, starting consumer #0, channel #0
test stopped (Consumer is idle for more than 1 second)
id: test-104850-534, sending rate avg: 0 msg/s
id: test-104850-534, receiving rate avg: 0 msg/s
```

The queue doesn't exist before using PerfTest and it behaves the same as if the queue did exist and was empty. I don't know if that's wanted or not. It's the same with empty and idle.

> Now let's try with several queues. We'll use only `--exit-when empty` this time.

For what it's worth, your instructions were using `idle`. I have confirmed both work.

**Comment by michaelklishin** [comment]
As far as `idle` goes, I think a missing and empty queue should be treated differently: the consumer/PerfTest is idle in both cases.

I don't know if it's important enough to bother with differentiating `empty` and "non-existent".

**Review by michaelklishin — APPROVED** [review]

**Comment by acogoluegnes** [comment]
> One thing I noticed is:
> 
> ```
> rabbitmq-perf-test-2.17.0-SNAPSHOT/bin/runjava com.rabbitmq.perf.PerfTest -x 0 -y 1 --queue test5 --predeclared --consumer-rate 10000 --exit-when idle
> id: test-104850-534, starting consumer #0
> id: test-104850-534, starting consumer #0, channel #0
> test stopped (Consumer is idle for more than 1 second)
> id: test-104850-534, sending rate avg: 0 msg/s
> id: test-104850-534, receiving rate avg: 0 msg/s
> ```
> 
> The queue doesn't exist before using PerfTest and it behaves the same as if the queue did exist and was empty. I don't know if that's wanted or not. It's the same with empty and idle.

Even though `--predeclared` is enabled, PerfTest check if the queue exists and creates it if it does not. This is exactly what we've been [discussing there](https://github.com/rabbitmq/rabbitmq-perf-test/issues/282#issuecomment-982525637), but for exchanges. This is the historical behavior of PerfTest.

So PerfTest creates the queue, registers a consumer, and the consumer stays idle for a couple of seconds, and exits. This is the expected behavior (the one I implemented and thought makes sense).

> 
> > Now let's try with several queues. We'll use only `--exit-when empty` this time.
> 
> For what it's worth, your instructions were using `idle`. I have confirmed both work.

Thanks, corrected.

**Comment by acogoluegnes** [comment]
> As far as `idle` goes, I think a missing and empty queue should be treated differently: the consumer/PerfTest is idle in both cases.
> 
> I don't know if it's important enough to bother with differentiating `empty` and "non-existent".

Yes, the missing queue case is an edge case. Currently PerfTest creates the queue anyway and exits because the consumer is idle.

**Pull request merged**
