### PR TITLE
Handle connection and topology recovery

### LINKED ISSUE #106: Connection recovery not working as expected
See the `README` [at this link](https://gist.github.com/lukebakken/39f786477d87b7dff6466b33461262af#file-readme-md). That gist contains a script that will reproduce the issue.

For what it's worth, this Python script does reconnect successfully so I'm pretty sure this isn't due to using `toxiproxy` - [pubsub.py.txt](https://github.com/rabbitmq/rabbitmq-perf-test/files/2203651/pubsub.py.txt)

### PR DESCRIPTION
**Pull request by acogoluegnes**
Fixes #106

### CODE REVIEW

**Comment by michaelklishin** [comment]
With this PR I can observe 3 different behaviors:

## Consumers Only, Recovery Enabled

Target node restarts result in successful connection recovery, as expected.

## Consumers Only, Recovery Disabled

Target node restarts do not result in successful connection recovery, and PerfTest does not shut down. Is this the behavior we want? @acogoluegnes @lukebakken @gerhard 

## Consumers and Publishers

Target node restarts result in an exception in the publisher that makes PerfTest terminate:

```
id: test-230128-665, time: 9.000s, sent: 17801 msg/s, received: 17332 msg/s, min/median/75th/95th/99th latency: 934246/1048948/1084794/1117263 µs
23:01:38.133 [AMQP Connection 127.0.0.1:5672] WARN  c.r.c.impl.ForgivingExceptionHandler - An unexpected connection driver error occured (Exception message: Connection reset)
23:01:38.140 [AMQP Connection 127.0.0.1:5672] WARN  c.r.c.impl.ForgivingExceptionHandler - An unexpected connection driver error occured (Exception message: Connection reset)
23:01:38.147 [RabbitMQ Error On Write Thread] ERROR c.r.c.impl.ForgivingExceptionHandler - An unexpected connection driver error occured
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at com.rabbitmq.client.impl.SocketFrameHandler.flush(SocketFrameHandler.java:177)
	at com.rabbitmq.client.impl.AMQConnection.flush(AMQConnection.java:571)
	at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:134)
	at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:447)
	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:423)
	at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:691)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:202)
	at com.rabbitmq.perf.Producer.publish(Producer.java:397)
	at com.rabbitmq.perf.Producer.lambda$handlePublish$21(Producer.java:358)
	at com.rabbitmq.perf.AgentBase.dealWithWriteOperation(AgentBase.java:83)
	at com.rabbitmq.perf.Producer.handlePublish(Producer.java:358)
	at com.rabbitmq.perf.Producer.run(Producer.java:284)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
23:01:38.147 [RabbitMQ Error On Write Thread] ERROR c.r.c.impl.ForgivingExceptionHandler - An unexpected connection driver error occured
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at com.rabbitmq.client.impl.SocketFrameHandler.flush(SocketFrameHandler.java:177)
	at com.rabbitmq.client.impl.AMQConnection.flush(AMQConnection.java:571)
	at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:134)
	at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:447)
	at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:429)
	at com.rabbitmq.client.impl.AMQConnection.handleConnectionClose(AMQConnection.java:846)
	at com.rabbitmq.client.impl.AMQConnection.processControlCommand(AMQConnection.java:799)
	at com.rabbitmq.client.impl.AMQConnection$1.processAsync(AMQConnection.java:242)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:178)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:111)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:650)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:597)
	at java.lang.Thread.run(Thread.java:748)
id: test-230128-665, sending rate avg: 19875 msg/s
id: test-230128-665, receiving rate avg: 18058 msg/s
```

Is this the behavior expected with recovery enabled?

**Comment by acogoluegnes** [comment]
@michaelklishin Thanks for looking into this.

For `Consumers Only, Recovery Disabled`, PerfTest is expected to crash, I fixed that.

For `Consumers and Publishers`, if connection recovery is enabled (this is the default), PerfTest shouldn't crash, it should recover for both producers and consumers. Can you share the steps to reproduce this?

**Comment by acogoluegnes** [comment]
@michaelklishin OK, scratch what I've said about the last repro, it's easy to reproduce without a publishing rate limit, and most of my tests were using a rate limit.

**Comment by acogoluegnes** [comment]
@michaelklishin I hopefully fixed the failing recovery, you can give another try.

**Comment by michaelklishin** [comment]
An update with the recent changes.

With this PR I can observe 3 different behaviors:

## Consumers Only, Recovery Enabled

Target node restarts result in successful connection recovery, as expected.

## Consumers Only, Recovery Disabled

Target node restarts result in a PerfTest shutdown, as expected.

## Consumers and Publishers

Target node restarts result in an exception in the publisher and successful connection recovery without excessive exception logging, as expected.

## Consumers and Publishers, Recovery Disabled

The behavior is the same as with just consumers and recovery disabled: an expected shutdown.

**Pull request merged**
