### PR TITLE
Add option to vary publishing rate

### LINKED ISSUE #192: Add option to vary publishing rate
It would be helpful to have the option of specifying a variable publishing rate, e.g.

```
bin/runjava com.rabbitmq.perf.PerfTest --variable-rate 1:10 --variable-rate 500:1
# each publisher will publish 1 msg/s for 10 seconds, then 500 msg/s for 1 second, then repeat this cycle ad infinitum
```

The thinking is `--variable-rate [RATE]:[DURATION]`, and the flag can be repeated same way as [docker's `--tag`](https://docs.docker.com/engine/reference/commandline/build/#tag-an-image--t) or [curl's `--header`](https://curl.haxx.se/docs/manpage.html#-H).

The goal is to simulate incoming message bursts. Message backlogs could be simulated in combination with `--consumer-latency`.

### PR DESCRIPTION
**Pull request by acogoluegnes**
[#165408174]

Fixes #192

### CODE REVIEW

**Comment by gerhard** [comment]
This is with `--variable-rate 10:30 --variable-rate 100:30`

image

image

One thing which I did not anticipate is how this will be specified via an environment variable. `VARIABLE_RATE` can only be defined once. As much as I like the clarity of `--variable-rate 10:30 --variable-rate 100:30`, I think `--variable-rate 10:30,100:30` would be better from the perspective of getting this to work via the env var, e.g. `VARIABLE_RATE=10:30,100:30`

What do you think Arnaud?

**Comment by acogoluegnes** [comment]
@gerhard `VARIABLE_RATE=10:30,100:30` should work as is, multiple-value options as environment variables are already supported.

**Comment by gerhard** [comment]
Yup, you're right, `VARIABLE_RATE=10:30,100:30` works as advertised. Let's capture this in the `--help --env` description. This is what we have currently for `VARIABLE_RATE`:

```
 VARIABLE_RATE                 variable publishing rate with
                               [RATE]:[DURATION] syntax, where [RATE] and
                               [DURATION] are positive integers. Use the
                               option several times to specify several
                               values.
```

Do you want to add something in the docs for this?

**Comment by gerhard** [comment]
It would be great to allow `0` as the rate. This would allow us to simulate no incoming messages, which is totally realistic and dope 😉

**Pull request merged**
