### PR TITLE
Support NIO

### LINKED ISSUE #83: Support NIO
This would help for high-load tests, as not every producer and consumer would use a IO reading thread.

### PR DESCRIPTION
**Pull request by acogoluegnes**
Fixes #83

### CODE REVIEW

**Comment by acogoluegnes** [comment]
@lukebakken Thanks for the QA. I fixed a couple of concurrency issues, the tests pass on my Linux laptop and on my MBP, but they can be flaky on some platforms (e.g. Travis CI). Could you give a try with the latest changes? On what platform are you running the tests?

**Comment by michaelklishin** [comment]
When I use `mvn clean; for i in {1..5}; do mvn test; done` to run the tests, I get

```
Running com.rabbitmq.perf.MessageCountTimeLimitAndPublishingIntervalRateTest
Tests run: 15, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 64.48 sec <<< FAILURE! - in com.rabbitmq.perf.MessageCountTimeLimitAndPublishingIntervalRateTest
timeLimitTakesPrecedenceOverCounts  Time elapsed: 10.454 sec  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: org.awaitility.core.ConditionFactory.untilAtomic Callable expected (<true> or <true>) but was <false> within 10 seconds.
	at com.rabbitmq.perf.MessageCountTimeLimitAndPublishingIntervalRateTest.timeLimitTakesPrecedenceOverCounts(MessageCountTimeLimitAndPublishingIntervalRateTest.java:284)

producerOnlyDoesNotStop  Time elapsed: 10.514 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Only 0 / 100 messages have been published ==> expected: <true> but was: <false>
	at com.rabbitmq.perf.MessageCountTimeLimitAndPublishingIntervalRateTest.producerOnlyDoesNotStop(MessageCountTimeLimitAndPublishingIntervalRateTest.java:338)
```

on the first couple of runs reliably. So there are still concurrency hazards and/or problematic tests.

**Comment by lukebakken** [comment]
I see the same as @michaelklishin - sometimes it works. I am running the tests on my linux workstation with this Java:

```
$ java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
```

**Comment by acogoluegnes** [comment]
@michaelklishin @lukebakken Just to be sure, have you tried with the latest update? And out of curiosity, can you try with the wrapper:

```
./mvnw clean; for i in {1..5}; do ./mvnw test; done
```

**Comment by michaelklishin** [comment]
Pulling reveals no new commits (other than in master). I'm getting the same failures with the wrapper.

**Comment by michaelklishin** [comment]
Per discussion with @acogoluegnes: we can reproduce 3 different failures in the same test on 4 different machines but not CI. Since it affects this PR, #82 and master roughly equally, we will rework the test in question independently.

**Comment by michaelklishin** [comment]
Note that by CI I do not mean Travis where we skip the test.

**Pull request merged**
