### PR TITLE
Arm arch support

### PR DESCRIPTION
**Pull request by rnsc**
This PR aims at detecting the architecture of the machine running the build to support ARM based computers.

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]

**Comment by acogoluegnes** [comment]
@rnsc Thanks for this contribution. Note as we build the PerfTest images on our CI that is running on x64, no arm64 image shoud be pushed when we release a new version. We'd be happy to change this and provide arm64 images (if possible on our CI).

**Comment by michaelklishin** [comment]
If we cannot change this easily, the users would be able to build images themselves and publish to a suitable registry 👍

**Comment by rnsc** [comment]
@acogoluegnes @michaelklishin Thanks for the merge. I wasn't expecting multi arch builds with this merge, but it would definitely be a nice addition!
Is it possible to just transform your "docker build [...]" into "docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v8 [...]", to have multiple archs available?

**Comment by michaelklishin** [comment]
@rnsc it depends on whether that requires the building machine to be an arm64 one. We will investigate.

**Comment by acogoluegnes** [comment]
I don't think the machine has to be an ARM64, this is the point of the buildx support in Docker. Our CI is running on Concourse, so this is where we have to look at.

**Comment by acogoluegnes** [comment]
After some research, the simplest option will be to move the Docker image build part to GitHub Actions. There are some caveats though: buildx and Java does not play well together as any Java command fails during the ARM64 build, so the ARM64 image will have to use a complete JDK instead of a custom JRE for AMD64 (build with `jlink`). The ARM64 image will be much bigger.

I did some experiments with the [*stream* performance tool](https://hub.docker.com/r/pivotalrabbitmq/stream-perf-test/tags?page=1&ordering=last_updated): 68 MB for the AMD64 image, 230 MB for the ARM64 one. It should be similar with PerfTest.

**Comment by acogoluegnes** [comment]
The Docker image for ARM64 is available:

```
$ docker run -it --rm pivotalrabbitmq/perf-test --version
RabbitMQ Perf Test 2.15.0 (f0df73a3a0f7a57d34fbe7741612eb31919cb76e; 2021-05-17T07:45:48Z)
RabbitMQ AMQP Client version: 5.12.0
Java version: 11.0.11, vendor: Azul Systems, Inc.
Java home: /usr/lib/jvm/java-1.11-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: Linux, version: 5.4.0-1045-aws, arch: aarch64
```

As advertised, it's significantly bigger than the AMD64 image (64 MB vs 226 MB), but it's there!

**Comment by rnsc** [comment]
@acogoluegnes Thank you!

**Pull request merged**
